const express = require('express');
const router = express.Router();
const campgrounds = require('../controllers/campgrounds');
const catchAsync = require('../utils/catchAsync');
const { isLoggedIn, validateCampground, isAuthor } = require('../middleware');

// the index route that shows all campgrounds
router.get('/', catchAsync(campgrounds.index));

// the new route that used to create a new campground
// order matters here, the new rout should be put before
// the /campground/:id route
router.get('/new', isLoggedIn, campgrounds.renderNewForm);

// the post route that update the database after 
// new campground is entered (generated by the form
// of the '/campgrounds/new' route)
router.post('/', 
    isLoggedIn, 
    validateCampground, 
    catchAsync(campgrounds.createCampground)
);

// the show route that display a single campground
router.get('/:id', catchAsync(campgrounds.showCampground));

// the route that servers a form to edit a campground
router.get('/:id/edit', 
    isLoggedIn, 
    isAuthor, 
    catchAsync(campgrounds.renderEditForm)
);

// the route that edits an campground entry in the database
router.put('/:id', 
    isLoggedIn, 
    isAuthor, 
    validateCampground, 
    catchAsync(campgrounds.updateCampground)
);

// delete route to delete a campground
router.delete('/:id', 
    isLoggedIn, 
    isAuthor, 
    catchAsync(campgrounds.deleteCampground)
);

module.exports = router;